### ISSUE TITLE
update_licenses should still run when repos don't have vendor folder

### ISSUE THREAD

**Issue by dprotaso** [knative/hack#315]
see discussion here: https://github.com/knative/pkg/pull/2810#discussion_r1319110291

Caused by #311

**Comment by evankanderson** [comment]
To provide additional context, this was original implemented to meet the second clause of the BSD 2-clause license:

> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

By embedding the license in the container image, people who received the OCI image would also receive a copy of the license, which would trivially satisfy "reproduce the above copyright notice".  Since I'm not a lawyer, I'm not going to venture whether this was an overly-restrictive reading of this clause.

**Comment by dprotaso** [comment]
I'm going to move my question to a public cncf foundation issue - it probably shouldn't be a service desk issue.

**Comment by dprotaso** [comment]
https://github.com/cncf/foundation/issues/642

**Comment by cardil** [comment]
@dprotaso I've opened the issue you mention: https://github.com/knative/community/issues/1441
